### ISSUE TITLE
htrun fails with RaaS version 0.9.0

### ISSUE THREAD

**Issue by studavekar** [ARMmbed/htrun#170]
```
[1507222815.67][urllib3.connectionpool]Starting new HTTP connection (1): austin-ci-linux-001.austin.arm.com
[1507222815.68][urllib3.connectionpool]http://austin-ci-linux-001.austin.arm.com:8000 "PUT /resource/0240000026334e45003840175c1a0048cb11000097969900/allocate HTTP/1.1" 200 1763
[1507222815.68][urllib3.connectionpool]Starting new HTTP connection (1): austin-ci-linux-001.austin.arm.com
[1507222815.68][urllib3.connectionpool]http://austin-ci-linux-001.austin.arm.com:8000 "PUT /resource/0240000026334e45003840175c1a0048cb11000097969900/disconnect HTTP/1.1" 400 74
[1507222815.68][GLRM][ERR] Disconnect request failed

[1507222815.68][urllib3.connectionpool]http://austin-ci-linux-001.austin.arm.com:8000 "PUT /resource/0240000026334e45003840175c1a0048cb11000097969900/disconnect HTTP/1.1" 400 74
[1507222815.68][GLRM][ERR] Disconnect request failed
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/arm/repo/htrun/mbed_host_tests/host_tests_conn_proxy/conn_proxy.py", line 176, in conn_process
    if not connector.write("mbed" * 10, log=True):
  File "/home/arm/repo/htrun/mbed_host_tests/host_tests_conn_proxy/conn_primitive_remote.py", line 138, in write
    self.selected_resource.write(payload)
  File "/home/arm/repo/raas/raas-pyclient/raas_client/resources/Base.py", line 545, in write
    format(Resource.CHANNEL_DEFAULT))
ResourceError: Attempted write when serial0 channel not open!
```

**Comment by studavekar** [comment]
Closing as fix is merged.
