### ISSUE TITLE
`mbedhtrun` without parameters causes unexpected exception

### ISSUE THREAD

**Issue by jupe** [ARMmbed/htrun#188]
`mbedhtrun` without parameters causes unexpected exception when running in macOS 10.13.4. Normal usage seems to work so probably not so critical issue. 
See traceback below:

```
$ mbedhtrun 
[1527328204.82][HTST][INF] host test executor ver. 1.3.1
[1527328204.82][HTST][INF] copy image onto target...
Traceback (most recent call last):
  File "/usr/local/bin/mbedhtrun", line 11, in <module>
    load_entry_point('mbed-host-tests', 'console_scripts', 'mbedhtrun')()
  File "/Users/jusvat01/Library/Python/2.7/lib/python/site-packages/mbed_host_tests/mbedhtrun.py", line 34, in main
    result = test_selector.execute()
  File "/Users/jusvat01/Library/Python/2.7/lib/python/site-packages/mbed_host_tests/host_tests_runner/host_test_default.py", line 517, in execute
    result = self.mbed.copy_image()
  File "/Users/jusvat01/Library/Python/2.7/lib/python/site-packages/mbed_host_tests/host_tests_runner/mbed_base.py", line 179, in copy_image
    initial_remount_count = get_remount_count(disk)
  File "/Users/jusvat01/Library/Python/2.7/lib/python/site-packages/mbed_host_tests/host_tests_runner/mbed_base.py", line 97, in get_remount_count
    files_on_disk = [x.upper() for x in os.listdir(disk_path)]
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-436

**Comment by theotherjimmy** [comment]
I can't reproduce this issue anymore.
