### ISSUE TITLE
Traceback on invalid character

### ISSUE THREAD

**Issue by c1728p9** [ARMmbed/htrun#206]
```
[1531774497.10][CONN][RXD] >>> 'Test attach_us for 500ms and time measure': 1 passed, 0 failed
[1531774497.10][CONN][RXD]
[1531774497.13][CONN][RXD] >>> Running case #9: 'Test detach'...
Process Process-1:
Traceback (most recent call last):
  File "c:\python27\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "c:\python27\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "c:\python27\lib\site-packages\mbed_host_tests\host_tests_conn_proxy\conn_proxy.py", line 257, in conn_process
    print_lines = kv_buffer.append(data)
  File "c:\python27\lib\site-packages\mbed_host_tests\host_tests_conn_proxy\conn_proxy.py", line 45, in append
    self.buff += payload.decode('utf-8')
  File "c:\python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 0: invalid start byte
```

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-1280
