### ISSUE TITLE
DefaultTestSelector - default ctor ends up with AttributeError

### ISSUE THREAD

**Issue by 0xc0170** [ARMmbed/htrun#36]
test_selector = DefaultTestSelector()

```
Traceback (most recent call last):
  File "..\test.py", line 96, in <module>
    test_selector = DefaultTestSelector()
  File "C:\Python27\lib\site-packages\mbed_host_tests\__init__.py", line 256, in __init__
    DefaultTestSelectorBase.__init__(self, options)
  File "C:\Python27\lib\site-packages\mbed_host_tests\host_tests_runner\host_test.py", line 216, in __init__
    Test.__init__(self, options=options)
  File "C:\Python27\lib\site-packages\mbed_host_tests\host_tests_runner\host_test.py", line 50, in __init__
    self.mbed = Mbed(options)
  File "C:\Python27\lib\site-packages\mbed_host_tests\host_tests_runner\mbed_base.py", line 50, in __init__
    self.port = self.options.port
AttributeError: 'NoneType' object has no attribute 'port'
```

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSYST-681

**Comment by PrzemekWirkus** [comment]
I will remove default value for ```DefaultTestSelector``` class, this is less flexible but will assume users are passing all options from command line to it.
